# Name of your GitHub Action workflow
name: Build cmake_flag Project

# This section controls WHEN the workflow runs
on:
  push:
    branches: [ main ]
    # The 'paths' filter ensures this workflow only runs if files inside
    # 'cmake_flag/' or the workflow file itself have changed.
    paths:
      - 'cmake_flag/**'
      - '.github/workflows/cmake_flag_build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'cmake_flag/**'
      - '.github/workflows/cmake_flag_build.yml'

  workflow_dispatch:
    # Defines inputs that will be presented in the GitHub UI
    inputs:
      preset:
        description: 'Which preset to build?'
        required: true
        default: 'default'
        type: choice
        options:
        - default
        - us-release

# A workflow run is made up of one or more jobs
jobs:
  build:
    # The type of machine to run the job on
    runs-on: ubuntu-latest

    # This sets the default working directory for all 'run' steps in this job.
    # It avoids having to 'cd cmake_flag' in every step.
    defaults:
      run:
        working-directory: ./cmake_flag

    # The sequence of tasks that will be executed
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure the CMake project using a preset
      - name: Configure CMake
        run: cmake --preset=${{ github.event.inputs.preset }}

      # 3. Build the project using the build preset
      - name: Build
        run: cmake --build --preset=${{ github.event.inputs.preset }}